name: actus

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - aeson
    - aeson-pretty
    - autodocodec
    - bytestring
    - conduit
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-text
    - genvalidity-time
    - pretty-show
    - really-safe-money
    - really-safe-money-autodocodec
    - really-safe-money-gen
    - scientific
    - text
    - time
    - typed-process
    - unliftio
    - validity
    - validity-containers
    - validity-scientific
    - validity-text
    - validity-time

executables:
  actus-test-harness:
    main: Main.hs
    source-dirs: harness
    ghc-options:            
    - -threaded
    - -rtsopts     
    - -with-rtsopts=-N
    dependencies:
    - actus

  actus-tester:
    main: Main.hs
    source-dirs: tester
    ghc-options:            
    - -threaded
    - -rtsopts     
    - -with-rtsopts=-N
    dependencies:
    - actus

tests:
  actus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools: sydtest-discover
    dependencies:
    - QuickCheck
    - actus
    - aeson
    - genvalidity
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - genvalidity-time
    - path
    - path-io
    - really-safe-money
    - really-safe-money-gen
    - sydtest
    - text
    - time
